spring.application.name=parallax

spring.datasource.url=jdbc:postgresql://dpg-d6lgsks50q8c73btp4c0-a.oregon-postgres.render.com:5432/parallax?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.username=parallax_user
spring.datasource.password=wQDZI2Lb8PdqBQarPG1DSqtfCcslNBJ2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.user.banned-words=admin,support,root,system,postmaster
spring.security.oauth2.client.registration.google.client-id=787059042613-b6b56oaemadf3vqdjl1j565ses90da45.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.github.client-id=Ov23liU8RnqHuvz9haco
spring.security.oauth2.client.registration.github.client-secret=6ae174f76e78412199082cbfc91a7b59d480bffa
spring.security.oauth2.client.registration.github.scope=user:email


app.jwt.secret=VGhpc0lzQVNlY3VyZUFwcFNlY3JldEtleTEyMzQ1Njc4OQ==

app.jwt.expiration-ms=3600000
app.jwt.refresh-expiration-ms=604800000


# Runner files
code.runner.image-name=py-collab-runner
code.session.image-name=py-collab-session


# Run code limits
code.runner.max-output-bytes=65536

parallax.storage.root=${user.home}/parallax
parallax.storage.sessions=${parallax.storage.root}/sessions
parallax.storage.projects=${parallax.storage.root}/projects

server.address=0.0.0.0
server.port=8080

code.runner.base-path=/var/code_sessions

server:
port: ${PORT:8080}
