package com.parallax.backend.parallax.service.project;

import com.parallax.backend.parallax.entity.file.ProjectFile;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Service
public class ProjectTemplateService {

    public List<ProjectFile> createDefaultFiles(UUID projectId, String language) {
        List<ProjectFile> files = new ArrayList<>();

        String mainFile = "README.md";
        String mainContent = "# New Project\n\nThis project was created in Parallax.";
        
        if (language != null) {
            switch (language.toLowerCase()) {
                case "python" -> {
                    mainFile = "main.py";
                    mainContent = "print('Hello from Parallax!')";
                }
                case "java" -> {
                    mainFile = "Main.java";
                    mainContent = "public class Main {\n    public static void main(String[] args) {\n        System.out.println(\"Hello from Parallax!\");\n    }\n}";
                }
                case "javascript", "typescript" -> {
                    mainFile = "index.js";
                    mainContent = "console.log('Hello from Parallax!');";
                }
                case "c" -> {
                    mainFile = "main.c";
                    mainContent = "#include <stdio.h>\n\nint main() {\n    printf(\"Hello from Parallax!\\n\");\n    return 0;\n}";
                }
                case "cpp" -> {
                    mainFile = "main.cpp";
                    mainContent = "#include <iostream>\n\nint main() {\n    std::cout << \"Hello from Parallax!\" << std::endl;\n    return 0;\n}";
                }
            }
        }

        files.add(new ProjectFile(
                UUID.randomUUID(),
                projectId,
                mainFile,
                mainContent,
                "FILE"
        ));

        if (!mainFile.equals("README.md")) {
            files.add(new ProjectFile(
                    UUID.randomUUID(),
                    projectId,
                    "README.md",
                    "# " + (language != null ? language.toUpperCase() : "New") + " Project\n\nGenerated by Parallax.",
                    "FILE"
            ));
        }

        return files;
    }
}
